name: Terraform CI - branches/PRs

on:
  pull_request:

jobs:
  terraform:
    if: >
      github.repository == vars.REPO_CAN_RUN_CI &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/envs/dev
    env:
      TF_VAR_repo_name: ${{ vars.TF_VAR_REPO_NAME }}
      TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_s3_bucket_name: ${{ secrets.TF_VAR_S3_BUCKET_NAME }}
      TF_VAR_s3_bucket_key: ${{ secrets.TF_VAR_S3_BUCKET_KEY }}
      TF_VAR_dynamodb_table_name: ${{ secrets.TF_VAR_DYNAMODB_TABLE_NAME }}
      TF_VAR_read_role_arn: ${{ secrets.TF_VAR_READ_ROLE_ARN }}
      TF_VAR_vpc_name: ${{ secrets.TF_VAR_VPC_NAME }}
      TF_VAR_vpc_cidr: ${{ secrets.TF_VAR_CIDR_BLOCK }}
      TF_VAR_azs: ${{ secrets.TF_VAR_AZS }}
      TF_VAR_private_subnets: ${{ secrets.TF_VAR_PRIVATE_SUBNETS }}
      TF_VAR_public_subnets: ${{ secrets.TF_VAR_PUBLIC_SUBNETS }}
      TF_VAR_cluster_name: ${{ secrets.TF_VAR_CLUSTER_NAME }}
      TF_VAR_enable_vpc_flow_logs: ${{ secrets.TF_VAR_ENABLE_VPC_FLOW_LOGS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (Read)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: $TF_VAR_read_role_arn
          aws-region: $TF_VAR_region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          TF_LOG=debug terraform init \
            -backend-config="bucket=$TF_VAR_s3_bucket_name" \
            -backend-config="key=$TF_VAR_s3_bucket_key" \
            -backend-config="region=$TF_VAR_region" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=$TF_VAR_dynamodb_table_name"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (no lock)
        run: terraform plan -lock=false

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        shell: bash
        run: |
          (
            set +e  # disable immediate exit on error
            checkov -d . --framework terraform --download-external-modules true --config-file ../../../.checkov.yml -o json > checkov.json
            status=$?
            if [ "$status" -ne 0 ]; then
              echo "❌ Checkov failed. Summary:"
              checkov -d . --framework terraform --download-external-modules true --config-file ../../../.checkov.yml -o cli

            fi
            exit $status
          )
