name: Terraform CI - branches/PRs

on:
  pull_request:

jobs:
  terraform:
    if: >
      github.repository == vars.REPO_CAN_RUN_CI &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/envs/dev
    env:
      ENV: ${{ vars.TF_VAR_ENVIRONMENT }}
      TF_VAR_repo_name: ${{ vars.TF_VAR_REPO_NAME }}
      TF_VAR_environment: ${{ env.ENV }}
      TF_VAR_enable_vpc_flow_logs: ${{ secrets.TF_VAR_ENABLE_VPC_FLOW_LOGS }}
      TF_VAR_tags: ${{ secrets.TF_VAR_TAGS }}

      TF_VAR_region: ${{ secrets[format('TF_VAR_{0}_REGION', env.ENV)] }}
      TF_VAR_vpc_name: ${{ secrets[format('TF_VAR_{0}_VPC_NAME', env.ENV)] }}
      TF_VAR_vpc_cidr: ${{ secrets[format('TF_VAR_{0}_CIDR_BLOCK', env.ENV)] }}
      TF_VAR_azs: ${{ secrets[format('TF_VAR_{0}_AZS', env.ENV)] }}
      TF_VAR_private_subnets: ${{ secrets[format('TF_VAR_{0}_PRIVATE_SUBNETS', env.ENV)] }}
      TF_VAR_public_subnets: ${{ secrets[format('TF_VAR_{0}_PUBLIC_SUBNETS', env.ENV)] }}
      TF_VAR_cluster_name: ${{ secrets[format('TF_VAR_{0}_CLUSTER_NAME', env.ENV)] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (Read)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets[format('TF_VAR_{0}_READ_ROLE_ARN', env.ENV)] }}
          aws-region: ${{ secrets[format('TF_VAR_{0}_REGION', env.ENV)] }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          TF_LOG=debug terraform init \
            -backend-config="bucket=${{ secrets[format('TF_VAR_{0}_S3_BUCKET_NAME', env.ENV)] }} \
            -backend-config="key=${{ secrets.TF_VAR_S3_BUCKET_KEY }}" \
            -backend-config="region=${{ secrets[format('TF_VAR_{0}_REGION', env.ENV)] }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets[format('TF_VAR_{0}_DYNAMODB_TABLE_NAME', env.ENV)] }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (no lock)
        run: terraform plan -lock=false

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        shell: bash
        run: |
          (
            set +e  # disable immediate exit on error
            checkov -d . --framework terraform --download-external-modules true --config-file ../../../.checkov.yml -o json > checkov.json
            status=$?
            if [ "$status" -ne 0 ]; then
              echo "❌ Checkov failed. Summary:"
              checkov -d . --framework terraform --download-external-modules true --config-file ../../../.checkov.yml -o cli

            fi
            exit $status
          )
