name: Terraform CI

on:
  push:
    branches: [main]

jobs:
  terraform:
    if: >
      github.repository == vars.REPO_CAN_RUN_CI &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform/envs/dev
    env:
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_vpc_name: ${{ secrets.TF_VAR_VPC_NAME }}
      TF_VAR_vpc_cidr: ${{ secrets.TF_VAR_CIDR_BLOCK }}
      TF_VAR_azs: ${{ secrets.TF_VAR_AZS }}
      TF_VAR_private_subnets: ${{ secrets.TF_VAR_PRIVATE_SUBNETS }}
      TF_VAR_public_subnets: ${{ secrets.TF_VAR_PUBLIC_SUBNETS }}
      TF_VAR_enable_vpc_flow_logs: ${{ secrets.TF_VAR_ENABLE_VPC_FLOW_LOGS }}
      TF_VAR_tags: ${{ secrets.TF_VAR_TAGS }}
      TF_VAR_cluster_name: ${{ secrets.TF_VAR_CLUSTER_NAME }}
      TF_VAR_environment: ${{ secrets.TF_VAR_ENVIRONMENT }}
      TF_VAR_repo_name: ${{ vars.REPO_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (Write)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TF_VAR_WRITE_ROLE_ARN }}
          aws-region: ${{ secrets.TF_VAR_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          TF_LOG=debug terraform init \
            -backend-config="bucket=${{ secrets.TF_VAR_S3_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TF_VAR_S3_BUCKET_KEY }}" \
            -backend-config="region=${{ secrets.TF_VAR_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.TF_VAR_DYNAMODB_TABLE_NAME }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (with lock)
        run: terraform plan

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        shell: bash
        run: |
          (
            set +e  # disable immediate exit on error
            checkov -d . --framework terraform --download-external-modules true --config-file ../../../.checkov.yml -o json > checkov.json
            status=$?
            if [ "$status" -ne 0 ]; then
              echo "❌ Checkov failed. Summary:"
              checkov -d . --framework terraform --download-external-modules true --config-file ../../../.checkov.yml -o cli

            fi
            exit $status
          )

      - name: Terraform Apply
        run: terraform apply -auto-approve
