name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/composition/dev

    env:
      TF_VAR_CIDR_BLOCK: ${{ secrets.TF_VAR_CIDR_BLOCK }}
      TF_VAR_ENVIRONMENT: ${{ secrets.TF_VAR_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TF_VAR_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.TF_VAR_AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          TF_LOG=debug terraform init \
            -backend-config="bucket=${{ secrets.TF_VAR_S3_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TF_VAR_S3_BUCKET_KEY }}" \
            -backend-config="region=${{ secrets.TF_VAR_AWS_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.TF_VAR_DYNAMODB_TABLE_NAME }}"

      - name: Terraform Validate
        if: github.ref != 'refs/heads/main'
        run: terraform validate

      - name: Terraform Plan
        run: TF_LOG=debug terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve